name: Terraform Destroy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  destroy-modules:
    if: contains(github.event.head_commit.message, '#destroy')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - api-gateway
          - ecs
          - ecr
          - iam
          - security
          - vpc
          # NÃO incluir: router53-acm, api-gateway-domain
    defaults:
      run:
        working-directory: infra/${{ matrix.module }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

  destroy-backend-bootstrap:
    if: contains(github.event.head_commit.message, '#destroy')
    needs: destroy-modules
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/backend-bootstrap
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      - name: Aviso sobre módulos não destruídos
        run: echo 'Os módulos router53-acm e api-gateway-domain NÃO são destruídos automaticamente para evitar custos extras com Route 53.' 